So the except block catches the error but doesn’t do anything with it.
True. 
So the program should only catch the specific class of errors that are expected, such as IOError in this case.
True. 
If that error is reported to the Python interpreter, the program is halted and the error is printed in the traceback ( list of function calls that were made before an exception stopped the program) at the interpreter prompt.
True. 
In this code the except block only contains the Python pass statement, which does nothing.
True. 
If the try block of code is executed without any errors, the except block of code is skipped.
True. 
